const routes = {
    notFound: "*",
    home: "/",
    news: "/news",
    articleDetail: "/news/:id",
    timeline: "/timeline",
    periodDetail: "/timeline/:id",
    characters: "/characters",
    events: "/events",
    eventDetail: "/events/:id",
    locations: "/locations",
    locationDetail: "/locations/:id",
    figureDetail: "/characters/:id",
    register: "/register",
    login: "/login",
    profile: "/profile",
    userArticles: "/my-articles",
    admin: "/admin",
    adminLogin: "/admin/login",
    adminDashboard: "/admin/dashboard",
    adminReportPrint: "/admin/report-print",
    adminUsers: "/admin/users",
    adminEvents: "/admin/events",
    adminFigures: "/admin/figures",
    adminLocations: "/admin/locations",
    adminPeriods: "/admin/periods",
    adminArticles: "/admin/articles",
    adminProfile: "/admin/profile",
    periodPreview: "/admin/preview/periods/:id",
    locationPreview: "/admin/preview/locations/:id",
    figurePreview: "/admin/preview/figures/:id",
    eventPreview: "/admin/preview/events/:id",
    articlePreview: "/admin/preview/articles/:id",
};

export default routes;
